#!/usr/bin/env bash
# This script installs Nginx on an Ubuntu machine and configures it to meet specified requirements
#+	Update package list and install Nginx
#+	Ensure Nginx is listening on port 80
#++	Reload Nginx configuration without using systemctl
#+++	Create a simple HTML page with the content "Hello World!"

apt-get update -y
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

printf %s "server {
	listen      80 default_server;
	listen      [::]:80 default_server;
	root        /etc/nginx/html;
	index       index.html index.htm;
}" > /etc/nginx/sites-available/default

service nginx restart
