#!/usr/bin/env bash
# This script configures Nginx to redirect /redirect_me to another page with a "301 Moved Permanently"
# Install Nginx if not already installed
# Create a simple HTML page for redirection
# Configure Nginx to perform the redirection
# Reload Nginx configuration without using systemctl

apt-get update -y
apt-get install -y nginx

echo '<html><head><meta http-equiv="refresh" content="0;url=https://www.youtube.com/watch?v=QH2-TGUlwu4"></head></html>' > /usr/share/nginx/html/redirect_me.html

printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /usr/share/nginx/html;
	index index.html index.htm;
	location /redirect_me {
		rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
