#!/usr/bin/env bash
# This script configures Nginx to have a custom 404 page with the string "Ceci n'est pas une page"
# Install Nginx if not already installed
# Create a simple HTML page for the custom 404
# Configure Nginx to use the custom 404 page
# Reload Nginx configuration without using systemctl

apt-get -y update
apt-get install -y nginx

echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default

service nginx restart
