#!/usr/bin/env bash
# This script installs and configures HAProxy on a new Ubuntu machine

sudo -i
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i "9i ENABLED=1" /etc/default/haproxy
cat >> /etc/haproxy/haproxy.cfg <<EOF

frontend haproxynode
    bind *:80
    mode http
    default_backend backend_nodes

backend backend_nodes
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    server 308631-web-01 54.210.107.201:80 check
    server 308631-web-02 54.237.76.82:80 check

EOF
sudo service haproxy restart
