#!/usr/bin/env bash
# This script generates a MySQL dump and creates a compressed archive out of it.

# MySQL dump file name
dump_file="backup.sql"

# Compressed archive name format: day-month-year.tar.gz
archive_name="$(date +'%d-%m-%Y').tar.gz"

# MySQL root password
mysql_password="$1"

# Generate MySQL dump
mysqldump -u root -p"$mysql_password" --all-databases > "$dump_file"

# Create a compressed archive
tar -czf "$archive_name" "$dump_file"
