#!/usr/bin/env bash
# This script pings an IP address passed as an argument.
#	Check if an IP address argument is provided
#	Extract the IP address from the argument
#	Ping the IP address 5 times

ip_address="$1"

if [ $# -ne 1 ];
then
	script_name=$(basename "$0")
	echo "Usage: $script_name {IP_ADDRESS}"
	exit 1
else
	ping -c 5 "$ip_address"
fi
