#!/usr/bin/env bash
# This script fixes Nginx to listen on port 80 in 5 lines or less
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
