#!/usr/bin/env bash
# This script creates a PID file, displays messages, and responds to signals

terminate_process() {
	rm /var/run/myscript.pid
	exit 0
}

echo "$$" > /var/run/myscript.pid

while true;
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminate_process' SIGTERM
	trap 'terminate_process' SIGQUIT
done
