#!/usr/bin/env bash
# This init script manages the manage_my_process script.

PID_FILE="/var/run/my_process.pid"

start_manage_my_process() {
	if [ -f "$PID_FILE" ];
	then
		echo "manage_my_process is already running."
	else
		./manage_my_process &
		echo $! > "$PID_FILE"
		echo "manage_my_process started"
	fi
}

stop_manage_my_process() {
	if [ -f "$PID_FILE" ];
	then
		kill $(cat "$PID_FILE")
		rm "$PID_FILE"
		echo "manage_my_process stopped"
	else
		echo "manage_my_process is not running."
	fi
}

restart_manage_my_process() {
	kill $(cat "$PID_FILE")
	rm "$PID_FILE"
	./manage_my_process &
	echo $! > "$PID_FILE"
	echo "manage_my_process restarted"
}

if [ $# -eq 0 ];
then
	echo "Usage: $0 {start|stop|restart}"
	exit 1
fi

case $1 in
	"start")
		start_manage_my_process
		;;
	"stop")
		stop_manage_my_process
		;;
	"restart")
		restart_manage_my_process
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
