#!/usr/bin/env bash
# This init script manages the manage_my_process script.

PID_FILE="/var/run/my_process.pid"

start_manage_my_process() {
	./manage_my_process &
	echo $! > "$PID_FILE"
	echo "manage_my_process started"
}

stop_manage_my_process() {
	kill "$(cat "$PID_FILE")"
	rm "$PID_FILE"
	echo "manage_my_process stopped"
}

restart_manage_my_process() {
	kill "$(cat "$PID_FILE")"
	rm "$PID_FILE"
	./manage_my_process &
	echo $! > "$PID_FILE"
	echo "manage_my_process restarted"
}

if [ $# -eq 0 ];
then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
fi

case $1 in
	"start")
		start_manage_my_process
		;;
	"stop")
		stop_manage_my_process
		;;
	"restart")
		restart_manage_my_process
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac
