#!/usr/bin/env bash
# This script displays lines containing the word "bash" and shows the PID of your Bash process
# shellcheck disable=SC2009
# Use ps and grep to filter lines containing "bash" and exclude the grep command itself

ps aux | grep bash | grep -v grep
