#!/usr/bin/env bash
# This script displays a message and sleeps between iterations
#	- Trap the SIGTERM signal and associate it with the handle_sigterm function
#	- Infinite loop with sleep

while true;
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible"' SIGTERM
done
