#!/usr/bin/env bash
# This script displays a message and sleeps between iterations
#	- Function to handle SIGTERM signal
#	- Trap the SIGTERM signal and associate it with the handle_sigterm function
#	- Infinite loop with sleep

handle_sigterm() {
	echo "I am invincible!!!"
	exit 0
}

trap 'handle_sigterm' SIGTERM

while :;
do
	echo "To infinity and beyond"
	sleep 2
done
