#!/usr/bin/env bash
# This script uses while loop to display the username, user ID, and home directory path from /etc/passwd.
#	Use a while loop to read the /etc/passwd file line by line

while IFS=":" read -r username _ userid _ _ homedir _
do
	echo "$username:$userid:$homedir"
done < /etc/passwd
