#!/usr/bin/env bash
# This script uses while loop to tell a story about users in /etc/passwd.
#	Use a while loop to read the /etc/passwd file line by line

while IFS=':' read username password uid gid info home shell;
do
	echo "The user $username is part of the $gid gang,"\
	"lives in $home and rides $shell."\
	"$uid's place is protected by the passcode $password,"\
	"more info about the user here: $info"
done < /etc/passwd
