#!/usr/bin/env bash
# This script parses the Apache log file and displays visitor IP along with HTTP status code.
#	Use awk to parse the log file and extract IP and HTTP status code

awk '{print $1, $9}' apache-access.log
