#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, sorts the data, and displays it.
#	Use awk to count occurrences, group by IP and HTTP status code, and format the output

awk '{ print $1, $9}' apache-access.log | sort | uniq -c | sort -rn
