#!/usr/bin/env bash
# This script uses while loop to display the time in a 12-hour format,
#	with hours from 0 to 12 and minutes from 1 to 59.

hour=0
minute=1

while [ "$hour" -le 12 ]
do
	echo "Hour: $hour"
	while [ "$minute" -le 59 ]
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
	minute=1
done
