#!/usr/bin/env bash
# This script configures the resolution of localhost and facebook.com on an Ubuntu server.

sudo cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
