#!/usr/bin/env bash
# This script reloads Gunicorn gracefully to avoid downtime

# ps aux | grep gunicorn | awk '{ print $2 }' | xargs kill -HUP
pgrep aux | pgrep gunicorn | awk '{ print $2 }' | xargs kill -HUP
